# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='project.Item'),
        ),
    ]
