# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cart',
        ),
    ]
