# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('state_code', models.CharField(default='', max_length=5)),
                ('contact', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
