# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20171001_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='project.Item'),
        ),
    ]
