# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_cart'),
        ('invoice', '0003_auto_20171001_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='project.Item'),
        ),
    ]
